version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'desafioToroDb'
      MYSQL_USER: 'toroUser'
      MYSQL_PASSWORD: 'toro_toro123'
      MYSQL_ROOT_PASSWORD: 'toro_toro123'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-compose-network 

  desafio-toro-backend:
    image: dnr1313/desafio-toro-backend
    ports: 
      - "5000:5000"
    restart: always
    networks:
      - mysql-compose-network
    depends_on:
      - mysql

  desafio-toro-frontend:
    image: dnr1313/desafio-toro-frontend
    ports: 
      - "4200:80"
    restart: always
    networks:
      - mysql-compose-network
    depends_on:
      - desafio-toro-backend
 
networks: 
   mysql-compose-network:
      driver: bridge
volumes:
   mysql_data:      