#Desafio Toro - US TORO-004
CREATE DATABASE desafioToro;
USE desafioToro;

CREATE TABLE User (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Cpf VARCHAR(11) NOT NULL, 
  Account VARCHAR(12) NOT NULL, 
  Balance DECIMAL(28, 8) NOT NULL DEFAULT 0, 
  PRIMARY KEY (Id))
ENGINE = INNODB;

CREATE TABLE Stock (
  Id INT NOT NULL AUTO_INCREMENT,
  Symbol VARCHAR(10) NOT NULL, 
  CurrentPrice DECIMAL(28, 8) NOT NULL, 
  PRIMARY KEY (Id))
ENGINE = INNODB;

CREATE TABLE Asset (
  Id INT NOT NULL AUTO_INCREMENT,
  Quantity INT NOT NULL, 
  UserId INT NOT NULL, 
  StockId INT NOT NULL, 
  PRIMARY KEY (Id),
  INDEX `fk_Asset_User_idx` (UserId ASC) VISIBLE,
  CONSTRAINT `fk_Asset_User` FOREIGN KEY (UserId) REFERENCES User (Id),
  INDEX `fk_Asset_Stock_idx` (StockId ASC) VISIBLE,
  CONSTRAINT `fk_Stock_User` FOREIGN KEY (StockId) REFERENCES Stock (Id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION) 
ENGINE = INNODB;


